name: Compile the code as test

# https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release
# model taken from https://github.com/mockersf/kmanb/releases
# on: release

on:
  # At midnight on every Tuesday
  schedule:
    - cron: "0 0 * * 2"
  # Manually triggered
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      GMP_INCDIR: /usr/include
      GMP_CXX_LINK: "-lm -lgmp -lgmpxx"
      BOOST_INCDIR: "/usr/include"
      BOOST_LINK: "/usr/lib/x86_64-linux-gnu/libboost_serialization.a"
      EIGEN_PATH: /home/runner/work/opt/eigen
      NAUTY_PATH: /home/runner/work/opt/nauty
      NAUTY_INCLUDE: "-I/home/runner/work/opt/nauty/include"
      NAUTY_LINK: "/home/runner/work/opt/nauty/lib/libnauty_static.a"
      LIBBLISS_PATH: /home/runner/opt/libbliss
      LIBBLISS_INCDIR: /home/runner/opt/libbliss/include
      LIBBLISS_LINK: "-L/home/runner/opt/libbliss/lib -lbliss -Wl,-rpath,/home/runner/opt/libbliss/lib"
      MINISAT_INCLUDE: "-I/usr/include"
      MINISAT_CPP_LINK: "-lminisat -lz"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdbm-dev libsnappy-dev make pkg-config rlwrap software-properties-common zlib1g-dev
          sudo apt-get install -y g++ gcc cmake libgmp-dev minisat autoconf autotools-dev libtool
          sudo apt-get install -y libboost-dev libboost-mpi-dev libboost-serialization-dev

      - name: Build test code
        run: |
          ls
          echo "After ls"

          pwd
          echo "After pwd"

          # NAUTY
          mkdir ExternalLib/nauty/build
          cd ExternalLib/nauty/build && cmake -DCMAKE_INSTALL_PREFIX:PATH=$NAUTY_PATH .. && make all install && cd ../../..
          pwd
          echo "After nauty compilation"

          # BLISS
          cd /home/runner && unzip work/basic_common_cpp/basic_common_cpp/ExternalLib/bliss-0.77.zip
          mkdir -p /home/runner/opt/libbliss/lib
          mkdir -p /home/runner/opt/libbliss/include
          cd /home/runner/opt/libbliss/lib && cmake /home/runner/bliss-0.77 && make
          cd /home/runner/opt/libbliss/include && cp /home/runner/bliss-0.77/src/*.hh .
          cd /home/runner/work/basic_common_cpp/basic_common_cpp
          pwd
          echo "After bliss compilation"

          # EIGEN
          # We need specific version 3.3.9 because of a bug in 3.4.0 for algebraic data types.
          wget -q https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz
          tar -xzf eigen-3.3.9.tar.gz
          mv eigen-3.3.9 /home/runner/work/opt/eigen
          pwd
          echo "After eigen-3.3.9 set up"

          ./compile.sh
          echo "After the compilation of the code"